#   Copyright 2019 Illumio, Inc.
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.


#AWS Security Hub Action Lambda function to act on Illumio Security Hub findings
AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  SecHubQuarantine:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: >-
        arn:aws:iam::<IAM role for the Lambda function>
      Events:
        CloudWatchEvent1:
          Type: CloudWatchEvent
          Properties:
            Pattern:
              resources:
                - >-
                  arn:aws:securityhub:<Custom Action ARN for Lambda integration>
              source:
                - aws.securityhub
      Environment:
        Variables:
          ILO_API_VERSION: '' #Illumio API version
          ENV_LABEL: '' #Illumio Environment Label for Quarantine
          ILO_API_KEY_SECRET: # Illumio PCE API KEY secret
          ILO_ORG_ID: '' # Illumio Org ID for this deployment
          ILO_API_KEY_ID: #Illumio API KEY
          ILO_PORT: '' # Illumio Port for API access
          LOC_LABEL: # Illumio Location label for Quarantine
          APP_LABEL: # Illumio Application Label for Quarantine
          ILLUMIO_SERVER: # Illumio PCE URL without https 
